"""Pydantic schemas for Chat API request payloads and response structures."""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime


class ChatRequest(BaseModel):
    """Schema validating incoming user chat request payload.

    Attributes:
        conversation_id (Optional[str]): Target conversation UUID (creates new session if omitted).
        message (str): Natural language message prompt (1 to 5000 characters).
    """

    conversation_id: Optional[str] = Field(
        default=None,
        description="Existing conversation ID (creates new conversation if not provided)",
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="User's natural language message prompt (max 5000 characters)",
    )


class ToolCallInfo(BaseModel):
    """Schema representing metadata for an invoked agent tool.

    Attributes:
        tool_name (str): Identifier name of the tool executed.
        arguments (Dict[str, Any]): Dictionary of arguments supplied to tool.
        result (Optional[str]): Output result text returned by tool execution.
    """

    tool_name: str = Field(description="Name of tool executed by agent")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Keyword arguments passed to tool")
    result: Optional[str] = Field(default=None, description="Execution result string returned by tool")


class ChatResponse(BaseModel):
    """Schema returned after processing a non-streaming chat request.

    Attributes:
        conversation_id (str): Conversation UUID associated with the chat exchange.
        response (str): Final textual reply generated by the AI assistant agent.
    """

    conversation_id: str = Field(description="Unique conversation identifier UUID")
    response: str = Field(description="Textual response generated by AI assistant")


class ChatMessageSchema(BaseModel):
    """Schema representing a single message entry within conversation history.

    Attributes:
        role (str): Message sender role ('user' or 'assistant').
        content (str): Content body text of the message.
    """

    role: str = Field(description="Message role ('user' or 'assistant')")
    content: str = Field(description="Message content text")


class ChatHistoryResponse(BaseModel):
    """Schema wrapping chat history payload for a conversation session.

    Attributes:
        conversation_id (Optional[str]): Target conversation UUID or None if empty.
        messages (List[ChatMessageSchema]): Chronological list of message schemas.
    """

    conversation_id: Optional[str] = Field(
        default=None, description="Target conversation UUID, or None if no conversation exists"
    )
    messages: List[ChatMessageSchema] = Field(
        default_factory=list, description="Chronological list of chat messages"
    )


class ConversationSummary(BaseModel):
    """Schema representing high-level summary metadata of a user conversation.

    Attributes:
        id (str): Conversation primary key UUID string.
        created_at (datetime): UTC creation timestamp.
        updated_at (Optional[datetime]): UTC timestamp of last message in conversation.
        message_count (int): Total message count.
        first_message_preview (Optional[str]): Text preview of the first message.
    """

    id: str = Field(description="Conversation primary key UUID string")
    created_at: datetime = Field(description="UTC timestamp when conversation was initiated")
    updated_at: Optional[datetime] = Field(None, description="UTC timestamp of last message activity")
    message_count: int = Field(description="Total count of messages in conversation")
    first_message_preview: Optional[str] = Field(
        default=None, description="First message text content preview"
    )


class ConversationListResponse(BaseModel):
    """Schema wrapping a paginated or bulk list of user conversation summaries.

    Attributes:
        conversations (List[ConversationSummary]): List of conversation metadata summaries.
        total (int): Total number of conversations matching request.
    """

    conversations: List[ConversationSummary] = Field(
        default_factory=list, description="List of conversation summary objects"
    )
    total: int = Field(description="Total count of conversations")
